- name: Provision a Jenkins CI server with Checkbox.io and Itrust
  hosts: all

  vars_prompt:
  - name: git_username
    prompt: Please enter your github username
    private: no

  - name: git_password
    prompt: Please enter your github password
    private: yes

  gather_facts: no
  pre_tasks:
    - name: Install Python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
      become: yes
    - setup: # aka gather_facts

  # pre_tasks:
  #   - name: Install Python for Ansible
  #     raw: (apt -y update && apt install -y python-minimal)
  #     changed_when: False
  #     become: yes
  #   - setup: # aka gather_facts

  vars:
    jenkins_init_file: /etc/default/jenkins
    jenkins_http_port_param: HTTP_PORT
    jenkins_java_options_env_var: JAVA_ARGS
    jenkins_hostname: "{{ansible_all_ipv4_addresses[0]}}"
    jenkins_http_port: 8080
    jenkins_jar_location: /opt/jenkins-cli.jar

    jenkins_build_jobs:
    - name: "Checkbox"
      xml_name: "checkbox_template.xml"
    - name: "Itrust"
      xml_name: "itrust_template.xml"

    jenkins_itrust_workspace: /var/lib/jenkins/jobs/{{jenkins_build_jobs[1].name}}/workspace/

  roles:
    - jenkins
    # - itrust
    # - fuzzer
    - checkbox

  # tasks:
  #   - name: Trigger Build Jobs
  #     hell: "java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}  build Checkbox"