  - name: Install Nodejs
    sudo: yes
    apt: name=nodejs state=present

#Checkbox Analyzer  
  - name: Copy Checkbox sites javascripts to remote
    copy:
      src: "{{checkbox_source}}"
      dest: "{{checkbox_location}}"
      directory_mode: '0777'

  - name : npm install
    shell: npm install
    args:
      chdir: /home/{{ansible_ssh_user}}/CheckboxAnalyzer/

  - name: Trigger Build Jobs
    shell: "java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}  build Checkbox"