- name: Copy fuzzer javascript tool to remote
  copy:
    src: /vagrant_data/Fuzzer
    dest: "{{fuzzer_location}}"
    directory_mode: '0777'

- name: Install packages based on package.json.
  npm:
    path: "{{fuzzer_location}}/Fuzzer"

- name: Add Nodesource Apt Sources
  become: yes
  apt_repository:
    repo: '{{ item }}'
    state: present
  with_items:
    - 'deb https://deb.nodesource.com/node_8.x trusty main'
    - 'deb-src https://deb.nodesource.com/node_8.x trusty main'

- name: Install NodeJS
  become: yes
  apt:
    name: nodejs
    state: latest
    force: yes
    update_cache: yes

- name: Git User Email
  command: git config --global user.email "{{ git_username }}"
  args:
    chdir: "{{jenkins_itrust_workspace}}"
  become: yes

# - debug:
#     msg: "{{output}}"

- include: fuzzer_core.yml
  with_sequence: start=1 end=100